/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {

        //first day
        FirstDay firstDay = new FirstDay();

        int[] solutions = new int[]{10, 15, 3, 7};

        firstDay.solution(solutions,17);
    }
}
